### ISSUE TITLE
Typo in README Installation Instructions

### ISSUE THREAD

**Issue by hamidrezafarzin** [MSC72m/seo_anlyzer#1]
Hi
In the "Installation" section of the README, there's a typo in the commands provided. Specifically, the cd command refers to seo-analyzer_api, which is inconsistent with the cloned repository name seo-analyzer-api.

Suggested Correction:
Please update the README as follows:

```bash
# Installation
Clone the repository:
git clone https://github.com/MSC72m/seo_analyzer.git
cd seo_analyzer
```
Thank you for your attention to this detail!

**Comment by MSC72m** [comment]
Dear Hamid Reza,

Thank you for taking the time to review the repository and for bringing this issue to attention. I appreciate your thorough feedback, and I wanted to let you know that we will address the mentioned issue.

Best regards,
Mohammad Sadeghian

**Comment by hamidrezafarzin** [comment]
thanks <3
